vim.pack.add { 'https://github.com/nvim-treesitter/nvim-treesitter-textobjects' }

-- require('nvim-treesitter.configs').setup {
--   textobjects = {
--     move = {
--       enable = true,
--       set_jumps = true,
--       goto_next_start = {
--         [']m'] = '@function.outer',
--         [']]'] = { query = '@class.outer', desc = 'Next class start' },
--       },
--       goto_previous_start = {
--         ['[m'] = '@function.outer',
--         ['[['] = '@class.outer',
--       },
--       goto_next = {
--         [']d'] = '@conditional.outer',
--       },
--       goto_previous = {
--         ['[d'] = '@conditional.outer',
--       },
--     },
--   },
-- }
